language: cpp
sudo: required

services:
- docker

compiler:
 - gcc
 - clang
 
env:
  global:
   - DOCKER_IMAGE=krab90/ubuntu-qt5:18.04_5.9.5
  matrix:
   - BUILD_SYSTEM=cmake
   - BUILD_SYSTEM=qmake

before_install:
 - docker pull $DOCKER_IMAGE

# TODO use system minizip https://bugs.launchpad.net/ubuntu/+bug/1182025
script:
 - docker run -it -v $PWD:$PWD -w $PWD $DOCKER_IMAGE /bin/bash -c "mkdir _build && cd _build && bash -c \"if [ '$BUILD_SYSTEM' = 'cmake' ]; then rm -r ../src/thirdparty/hunspell ../src/thirdparty/idn ../src/thirdparty/zlib && cmake -DCMAKE_C_COMPILER=/usr/bin/$CC -DCMAKE_CXX_COMPILER=/usr/bin/$CXX -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_LIB_DIR=lib64 -DINSTALL_SDK=ON -DSPELLCHECKER_BACKEND=hunspell -G Ninja  ../ && ninja -j4 && ninja install; else qmake QMAKE_CC=$CC QMAKE_CXX=$CXX CONFIG-=debug_and_release CONFIG-=debug CONFIG+=release INSTALL_PREFIX=/usr INSTALL_LIB_DIR=lib64 ../vacuum.pro && make -j4 && make install; fi\" && du -sc /usr/bin/vacuum /usr/include/vacuum/ /usr/lib64/libvacuumutils.so* /usr/lib*/vacuum/plugins/ /usr/share/vacuum/{resources,translations}/"
