#ifndef DEF_MULTIUSERDATAHOLDERORDERS_H
#define DEF_MULTIUSERDATAHOLDERORDERS_H

#define MUDHO_MULTIUSERCHAT              1000
#define MUDHO_CLIENTICONS                2000

#endif // DEF_MULTIUSERDATAHOLDERORDERS_H
